# Generated by Django 4.2.3 on 2023-07-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("list", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(null=True),
        ),
    ]
